apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-butler-agent
  namespace: ops-butler
  labels:
    app: ops-butler-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-butler-agent
  template:
    metadata:
      labels:
        app: ops-butler-agent
    spec:
      serviceAccountName: ops-butler-agent
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: agent
        image: crcoerph/ops-butler:agent-v0.0.1-01
        imagePullPolicy: Always
        env:
        - name: API_SERVER
          value: ops-butler-api:9090
        - name: CLUSTER_NAME
          value: local-dev
        - name: CLUSTER_LABELS
          value: env=dev,region=local
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-butler-agent
  namespace: ops-butler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ops-butler-agent
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-butler-agent
subjects:
- kind: ServiceAccount
  name: ops-butler-agent
  namespace: ops-butler
roleRef:
  kind: ClusterRole
  name: ops-butler-agent
  apiGroup: rbac.authorization.k8s.io
