apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-butler-api
  namespace: ops-butler
  labels:
    app: ops-butler-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-butler-api
  template:
    metadata:
      labels:
        app: ops-butler-api
    spec:
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: api
        image: crcoerph/ops-butler:api-v0.0.1-01
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        env:
        - name: DB_HOST
          value: ops-butler-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: ops_portal
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ops-butler-api
  namespace: ops-butler
  labels:
    app: ops-butler-api
spec:
  selector:
    app: ops-butler-api
  ports:
  - port: 8080
    targetPort: http
    name: http
  - port: 9090
    targetPort: grpc
    name: grpc
  type: ClusterIP
