apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ops-butler-db
  namespace: ops-butler
  labels:
    app: ops-butler-db
spec:
  serviceName: ops-butler-db
  replicas: 1
  selector:
    matchLabels:
      app: ops-butler-db
  template:
    metadata:
      labels:
        app: ops-butler-db
    spec:
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: ops_portal
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ops-butler-db
  namespace: ops-butler
  labels:
    app: ops-butler-db
spec:
  selector:
    app: ops-butler-db
  ports:
  - port: 5432
    targetPort: postgres
    name: postgres
  type: ClusterIP
