apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-butler-scheduler
  namespace: ops-butler
  labels:
    app: ops-butler-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-butler-scheduler
  template:
    metadata:
      labels:
        app: ops-butler-scheduler
    spec:
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: scheduler
        image: crcoerph/ops-butler:scheduler-v0.0.1-01
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: ops-butler-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: ops_portal
        - name: API_SERVER
          value: ops-butler-api:9090
        - name: REDIS_URL
          value: ops-butler-redis:6379
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
