apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-butler-web
  namespace: ops-butler
  labels:
    app: ops-butler-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-butler-web
  template:
    metadata:
      labels:
        app: ops-butler-web
    spec:
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: web
        image: crcoerph/ops-butler:web-v0.0.1-01
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: API_URL
          value: http://ops-butler-api:8080
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ops-butler-web
  namespace: ops-butler
  labels:
    app: ops-butler-web
spec:
  selector:
    app: ops-butler-web
  ports:
  - port: 80
    targetPort: http
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ops-butler-web-nodeport
  namespace: ops-butler
  labels:
    app: ops-butler-web
spec:
  selector:
    app: ops-butler-web
  ports:
  - port: 80
    targetPort: http
    nodePort: 30080
    name: http
  type: NodePort
